server:
  port: 8081


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userServices
    username: postgres
    password: Chetan.123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: User-Service

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka